image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      rustup default stable
      solana config set --url https://api.testnet.solana.com
    command: "bash"

ports:
  - port: 8899
    onOpen: open-preview
